### ISSUE TITLE
[REQUEST] Display Shop API

### ISSUE THREAD

**Issue by bzigus** [XZot1K/DisplayShopsAPI#2]
**In a couple of words, describe the feature you'd like to see:**
It would be a lot easier to be able to find a Shop via ID given to it. 

**Screenshots & Media**
A couple images, videos, or GIFs of how things sould look if possible.

`Shop shop = new Shop(DisplayShops.getPluginInstance().getManager().getShopUUID(ID);`

**Additional context**

**Comment by XZot1K** [comment]
This seems like something that could help speed up the add-on process and such I'll add in!

**Comment by XZot1K** [comment]
This feature has been added in 1.1.3!
