### ISSUE TITLE
[BUG] /ds copy

### ISSUE THREAD

**Issue by bzigus** [XZot1K/DisplayShopsAPI#3]
**Describe the bug**
When you do /ds copy, the test is not formatted correctly
**To Reproduce**
Steps to reproduce the bug:
1. run the command: `/ds copy` while looking at a shop
2. look at chat 
![image](https://user-images.githubusercontent.com/22013942/91649229-bba1be00-ea3f-11ea-8f9f-3fc956ef70ba.png)

**Expected behavior**
Color codes should properly work

**Screenshots & Other Media**
If applicable, add screenshots, GIFs, or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/22013942/91649234-c8bead00-ea3f-11ea-974f-365dc51e8374.png)

**Server Information (Please fill in the information below):**
 - Version: 1.8.9
 - Plugins: 
![image](https://user-images.githubusercontent.com/22013942/91649238-daa05000-ea3f-11ea-8b16-9b1e3776b3d5.png)

**Verification (REQUIRED - Only one is required):**
 - Spigot: PintoBean44
 - Mc-Market: none
 - Songoda: none
 - Version: 1.5.3

**Additional context**
Add any other context about the issue/bug here.

**Comment by XZot1K** [comment]
Beautiful information on this issue, I'll take a look and close this once it is resolved in a build!

**Comment by bzigus** [comment]
I've been on a plugin support team. Ik how annoying bad bug reports can be

**Comment by XZot1K** [comment]
This issue has been resolved after testing; however, if this issue persists feel free to re-open!
