### ISSUE TITLE
[REQUEST] Multiple Pages For Base Block Material Selection

### ISSUE THREAD

**Issue by SplashNetwork** [XZot1K/DisplayShopsAPI#5]
**In a couple of words, describe the feature you'd like to see:**
It would be great for the Base Block Selection Menu to allow multiple pages so I can have more than 54 options for customisation

**Screenshots & Media**
Happy to provide if necessary but I don't think it is for this idea as I'm sure you know the menu I mean

**Additional context**
I made a ticket on Discord but it was suggested to add it to the GitHub so thought I would 👍 

Hope you add this feature :D

**Comment by XZot1K** [comment]
This has been implemented in the newest release!
