### ISSUE TITLE
[ISSUE][REQUEST] Admin Shops Display Unlimited

### ISSUE THREAD

**Issue by ZiolaBleu** [XZot1K/DisplayShopsAPI#7]
I want Admin Shops to display "Unlimited" rather than 9999999; slowly subtracting from the original number. Similiar to how ShowCase Plugin allowed for you to sell "x amount" "x price" "unlimited"

/ds admin id:2 quantity to sell:64 price:400 stock:unlimited
/ds admin 2 64 400 unlimited

Also whenever you remove an admin shop, make the item/s just delete, not drop to the ground in a rage that causes the server to crash. 

If there is a way to do this, I did not see it; if you could please show me. But as it currently stands, when you delete a shop, the stock of that shop falls to the ground. So when you set the stock to 999999999 and delete it, you have 999999999 entities being generated.

**Comment by XZot1K** [comment]
> I want Admin Shops to display "Unlimited" rather than 9999999; slowly subtracting from the original number. Similiar to how ShowCase Plugin allowed for you to sell "x amount" "x price" "unlimited"
> 
> /ds admin id:2 quantity to sell:64 price:400 stock:unlimited
> /ds admin 2 64 400 unlimited
> 
> Also whenever you remove an admin shop, make the item/s just delete, not drop to the ground in a rage that causes the server to crash.
> 
> If there is a way to do this, I did not see it; if you could please show me. But as it currently stands, when you delete a shop, the stock of that shop falls to the ground. So when you set the stock to 999999999 and delete it, you have 999999999 entities being generated.

When using the issue tracker on the premium plugins be sure to always provide us username on spigot, mc-market, or songoda so we can confirm you are a valid user. The plugin has the goal to bring interaction to your shopping environment, the [Wiki](https://github.com/XZot1K/DisplayShopsAPI/wiki/shop-guide) may contain the information you require.

To help you out, use `/ds stock -1` to set admin shops into an unlimited mode. The second thing you mentioned tells me your plugin may be out of date as the default configuration has the option disabled in newer versions. 

`# If this option is enabled, shops will require the stock to be at zero before allowing actions such as shop deletion.
require-empty-stock: true`

For further assistance please refer to the support discord!

**Comment by ZiolaBleu** [comment]
And as for my question about removing space, is that possible? - ZiolaBleu

**Comment by ZiolaBleu** [comment]
My plugin was downloaded directly after purchase from Market

**Comment by ZiolaBleu** [comment]
So I think you're mistaken when you say, "by default." Because I watched as 9,999,999 blocks of grass dropped to the floor and crashed my server, by default.

**Comment by XZot1K** [comment]
> So I think you're mistaken when you say, "by default." Because I watched as 9,999,999 blocks of grass dropped to the floor and crashed my server, by default.

Your questions were answered in the previous message, to remove a limit, please use the provided command. The plugin has no form of block dropping enabled by default, this is confirmed as of version 1.5.8-B and 1.5.9 (beta) due to the option listed above in the config.yml.

The issue tracker was not intended to be open as we are providing support through the official pages or the discord. Please refer to those support methods from this point, as the tracker will be disabled. Hopefully, that information helps!
